### ISSUE TITLE
Android App TODO

### ISSUE THREAD

**Issue by wotomas** [depromeet/reasonable#4]
- [x] Header 디자인 적용
- [x] 검색 기능 추가(?)
- [x] Image 라이브러리 Picasso 적용
- [ ] Footer SNS 연동
- [ ] 디스크 Cache 연동 (성능 개선)
- [x] Detail View 적용

**Comment by wotomas** [comment]
헷갈려서 추가해놓음.. 끝내고 마스터로 merge 예정..
